-- phpMyAdmin SQL Dump
-- version 3.5.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 10, 2014 at 03:24 PM
-- Server version: 5.5.24-log
-- PHP Version: 5.4.3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `eine`
--

-- --------------------------------------------------------

--
-- Table structure for table `tovar`
--

CREATE TABLE IF NOT EXISTS `tovar` (
  `cena` double NOT NULL,
  `nazov` varchar(100) COLLATE utf8_slovak_ci NOT NULL,
  `vyrobca` varchar(50) COLLATE utf8_slovak_ci NOT NULL,
  `procesor` varchar(100) COLLATE utf8_slovak_ci NOT NULL,
  `procesor_vyrobca` varchar(50) COLLATE utf8_slovak_ci NOT NULL,
  `grafika` varchar(100) COLLATE utf8_slovak_ci NOT NULL,
  `grafika_vyrobca` varchar(50) COLLATE utf8_slovak_ci NOT NULL,
  `ram` varchar(20) COLLATE utf8_slovak_ci NOT NULL,
  `hdd` varchar(20) COLLATE utf8_slovak_ci NOT NULL,
  `uhlopriecka` double NOT NULL,
  `popis` text COLLATE utf8_slovak_ci NOT NULL,
  `slug` text COLLATE utf8_slovak_ci NOT NULL,
  `kusov` smallint(6) NOT NULL,
  `ID` int(11) NOT NULL,
  `pocet_obrazkov` smallint(6) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_slovak_ci;

--
-- Dumping data for table `tovar`
--

INSERT INTO `tovar` (`cena`, `nazov`, `vyrobca`, `procesor`, `procesor_vyrobca`, `grafika`, `grafika_vyrobca`, `ram`, `hdd`, `uhlopriecka`, `popis`, `slug`, `kusov`, `ID`, `pocet_obrazkov`) VALUES
(542.2, 'ASUS X550CC-XO175H', 'ASUS', 'Corei5', 'Intel', 'GT720M', 'NVidia', '2GB', '750GB', 15.6, 'Pokračovateľ populárnej série X je stelesnením elegancie a výkonu. Oproti predchodcovi ponúkne tenšie telo, Nižšiu hmotnosť a väčší výkon spojený s množstvom inovatívnych technológií. Moderné hardware zaručuje rýchlu odozvu v systéme, bezproblémové hranie hier a sledovanie videa v najvyššej kvalite. Notebook myslí aj na výdrž, ktorá sa vďaka najnovším technológiám výrazne predĺžila.\nAsus si veľmi zakladá na kvalitnom zvuku. Vyvinul spolu s SonicMaster väčšie reproduktory, Ktoré podávajú vernejšie a priestorovejší zvuk, Než konkurencia.\n\nSkrátka ponúka 100% zážitok pri sledovaní filmov, počúvanie muziky a hranie hier. Nemenej kvalitné webová kamera s citlivým snímačom dosahuje skvelých výsledkov aj pri zlých svetelných podmienkach.\n\n4-článková Li-Ion batéria prináša kapacitu 2600 mAh. Pomocou technológie ASUS Super Hybrid Engine II sa dá nastaviť mód spotreby, ktorý výrazne predlžuje chod notebooku. Všetky dáta a rozpracovanej práce sa automaticky uloží, Keď batérie klesne pod 5%. Technológia ďalej výrazne zrýchľuje štart systému. Prebudenie trvá podľa výrobcu len 2 sekundy.\nMultidotykový touchpad chápe interaktívne pohyby, Podobne ako tablet. Pomocou jednoduchých gest sa dá ľahko scrollovať, približovať alebo dostať do alternatívnej ponuky bez použitia myši. Klávesová tlačidlá sú ohraničené dostatočným priestorom pre minimalizáciu preklepov. Asus X550CC proste musíte mať.', 'Notebook - Intel Core i5 3337 Ivy Bridge, 15.6 "LED 1366x768 matný, RAM 6GB, NVIDIA GeForce GT 720M 2GB, HDD 750GB 5400 otáčok, DVD, WiFi, Bluetooth 4.0, webkamera, HDMI, USB 3.0, 4 článková batéria, Windows 8 64 - bit', 11, 0, 12),
(578.15, 'ASUS X75VB-TY010', 'ASUS', 'Corei5', 'Intel', 'GT740M', 'NVidia', '2GB', '750GB', 17.3, 'Podarený notebook X75VB od spoločnosti Asus zvádza výkonným procesorom Intel Core i5-3230 s jadrom Ivy Bridge, ktorý pracuje na frekvencii 2,6 GHz a v prípade potreby technológie Intel Turbo Boost 2 automaticky procesor přetaktuje až na 3,2 GHz. Procesor pracuje s operačnou pamäťou s celkovou veľkosťou 6 GB a grafickou kartouNVIDIA GeForce GT740 s vlastnou operačnou pamäťou o veľkosti2 GB. Vďaka tomuto vybaveniu plne uspokojí užívateľov, ktorí chcú multimediálny prenosný počítač, ktorý svižne zvláda aj herné zábavu. Technológia IceCool zaisťuje, že všetky komponenty generujúce teplo sú umiestnené ďalej od užívateľa, takže opierka dlaní ostáva príjemne chladná a pohodlie pri písaní si možno užívať aj po dlhšom používaní.\r\n\r\nDodávaná batéria poskytne mobilitu bez káblov až na 3 hodiny. Lákavou súčasťou notebooku je tiež zvukový systém Asus SonicMaster Lite. Ten zaistí zvukové podanie, ktorý podá v tejto triede notebookov bezkonkurenčné basy aj čisté výšky. Notebook sa dodávabez operačného systémua jeho voľba je čisto na vás. V našej ponuke nájdete ako Microsoft Windows 7, Tak modernejšie a čoraz populárnejší operačný systémMicrosoft Windows 8s množstvom nových a zaujímavých funkcií a vylepšení.\r\n\r\nVymoženosťou je ajASUS Super Hybrid Engine II s funkciou Instant On. Tá zariadi prechod z režimu spánku do 2 sekúnd! Ak si teda potrebujete odskočiť, a potom vás nebaví netrpezlivo čakať ako bude systém funkčný, táto funkcia vás tohto zbaví. Navyšedokáže automaticky zálohovať vaše dátav systéme Microsoft Windows 8, ak úroveň nabitia batérie klesne pod 5%.', 'Notebook - Intel Core i5 3230 Ivy Bridge, 17.3 "1600x900 lesklý, RAM 6GB, NVIDIA GeForce GT 740mm 2GB, HDD 750GB 5400 otáčok, DVD, WiFi, Bluetooth 4.0, webkamera, HDMI, USB 3.0, 6 článková batéria, bez operačného systému', 4, 1, 12),
(469.75, 'Lenovo IdeaPad B590', 'LENOVO', 'Corei3', 'Intel', 'HD4000', 'Intel', '4GB', '500GB', 15.6, 'Elegantný notebook spája univerzálnosť s dostupnou cenou. Vďaka odolnému telu a matnému displeji sa hodí predovšetkým pre prácu. Vďaka funkcii Lenovo Energy Management je na neho spoľahnutie po celých 6 hodín bez zásuvky. IdeaPad je serióznym spoločníkom každého obchodníka na cestách, a pre odreagovanie ponúkne decentný výkon. O ochranu pred cudzím prístupom sa postará čítačka odtlačkov prstov, Ktorá nepustí dovnútra nikoho iného.\r\nDisplej s uhlopriečkou 15,6 "je ideálny ako na prácu, tak prenášanie. Na obrazovku sa pohodlne zmestia aj 2 okná naraz. Rozmery a váha však zostávajú v rozumných medziach a IdeaPad si zachováva veľmi dobrú mobilitu. Matné prevedenie displeja zaručuje praktickosť a čitateľnosť. Pre komunikáciu tvárou v tvár poslúži, vo veku zabudovaná, HD webkamera.\r\nSilné CPU si zachová rýchlu odozvu aj prí viac otvorených aplikáciách. Technológia Intel Wireless Display sprístupní bezdrôtové pripojenie televízie, aneb projekciu na cestách. Integrovaná grafická karta ponúka dostatočný výkon, a zárove ňšetrí energiu, A tým predlžuje výdrž.\r\n\r\nKlávesnica AccuType maximalizuje komfort pri písaní. Špeciálna ergonómia, vyvýšené a prehnuté ostrovčeky spolu s expandovaným vonkajším priestorom, minimalizuje počet preklepov - Zrýchľuje prácu. Písanie čísiel značne uľahčí numerický blok na pravej strane.\r\nPripojiť k internetu sa dá pomocou kábla, alebo pohodlnejšieho riešenie v podobe bezdrôtové WiFi. Tá zaistí voľnosť pohybu pri surfovaní po internete alebo vybavovanie korešpondencie. Bluetooth pre diaľkové pripojenie mobilných zariadení je samozrejmosťou. O maximálnu konektivitu sa postarajú 4 USB porty.\r\n\r\nPrelomová dlaždicová plocha spolu s novým prostredím prináša ľahké a bezproblémové ovládanie nenáročného operačného systému Windows 8. Súčasťou je Windows Store s množstvom užitočných aplikácií na prevzatie, vrátane hier. Pre prezeranie webového obsahu poslúži inovatívne Internet Explorer 10.', 'Notebook - Intel Core i3 3110 Ivy Bridge, 15.6 "LED 1366x768 antireflexnou, RAM 4GB, Intel HD Graphics 4000, HDD 500GB 5400 otáčok, DVD, WiFi, Bluetooth 4.0, Webkamera 0.3 Mpx, HDMI, čítačka odtlačkov prstov, USB 3.0, Windows 8 64 -bit', 2, 2, 12),
(809, 'Lenovo IdeaPad Yoga 13 Silver Grey', 'LENOVO', 'Corei3', 'Intel', 'HD4000', 'Intel', '4GB', '128GB', 13.3, 'Yoga 13 od Lenova nie je len tak hocijakým ultrabookov. Dokáže sa totiž premeniť hneď vo štyri interaktívne zariadení a to púhym sklopením displeja až o 360 °. Kúpou jedného zariadenia tak získate tri ďalšie ako bonus. Klasický laptop dopĺňajú režimy stojanček, stan a tabliet. Displej s ultrajemným rozlíšením a IPS matricou patrí medzi ďalšie skvosty tohto zariadenia, u ktorého sa navyše na prvý pohľad môže zdať, že do tak tenkého tela sa nevošiel žiadny výkon, avšak opak je pravdou. Vybavený architektúrou Ivy Bridge sa vrhá do súboja s oveľa hrubšími a ťažšími kúsky, nad ktorými často vyhráva vo všetkých smeroch.\r\n\r\nPracujte maximálne efektívne a užívajte si ničím nebrzdené zábavu naplno s procesorom najvyššej rady Intel Core i3 3217 s dvojicou nekompromisne výkonných jadier. Extrémne nízku spotrebu si udržiava aj napriek tomu, že sám dokáže bežať na frekvencii až 1,8 GHz a spracovať naraz4 vlákna. Integrované grafické jadro Intel HD Graphics 4000 prevezme kormidlo pri sledovaní HD filmov alebo hranie hier v DirectX 11, kde dosahuje až o40% lepšie výkony než generácie predchádzajúcej.\r\n\r\nRozmaznávajte vaše oči nádherne farebným a kontrastným obrazom ultrabooku Yoga 13. Nielenže má na svoju uhlopriečku naozaj detailné rozlíšenie 1600 x 900 pixelov, Ale navyše je vyrobený technológiou IPS. Tá oproti klasickým TN panelom ponúkne neporovnateľne živšie farby plné detailov a lepšie pozorovacie uhly, Vďaka ktorým sa svojimi priateľmi okolo vás môžete o všetko podeliť. Ak pripočítame k tomu moderná LED podsvietenie, získavame špičkový displej, na ktorý sa budete chcieť stále pozerať.', 'Tablet PC - Certifikácia Ultrabook, Intel Core i3 3217 Ivy Bridge, multidotykový 13.3 "1600x900 IPS, Intel HD Graphics 4000, RAM 4GB, SSD 128GB, WiFi, Bluetooth 4.0, webkamera, HDMI, USB 3.0, 4 článková batéria, Windows 8 64-bit', 1, 3, 10),
(317.02, 'Packard Bell EasyNote TE69KB Silver', 'PACKARDBELL', 'Zacate', 'AMD', 'HD8240', 'AMD', '2GB', '500GB', 15.6, 'Elegantný notebook zaujme svojím strieborno-čiernym prevedením. TE69KB je určený pre multimediálne použitie. Vnútri schováva úsporný procesor AMD E1 - 2500 s 2 jadrami na frekvencii 1,4 GHz a TDP 15 W. Ten je podporený operačnou pamäťou DDR3 o veľkosti 2 GB s možnosťou rozšírenia až na 8 GB. S grafickým čipom AMD Radeon HD 8240 sa netreba báť náročnejších aplikácií. Všetko sa ukladá na pevný disk o kapacitou 500 GB. Batéria zabezpečí zábavu až na 3,5 hodiny.\r\n\r\nNotebook disponuje nielen silou, ale aj dostatočnú výbavou. Napriek tomu si zachovátenké šasi. Po stranách má DVD mechaniku, čítačku pamäťových kariet, HDMI výstup,USB 3.0a dvojicu USB 2.0 portov. Klávesnica obsahuje rad multimediálnych tlačidiel pre jednoduché ovládanie, vrátane numerickej klávesnice.\r\n\r\nPripojiť k internetu sa dá pomocou kábla, alebo pohodlnejšieho riešenie v podobe bezdrôtové WiFi. Tá zaistí voľnosť pohybu pri surfovaní po internete alebo komunikácia tvárou v tvár pomocou HD webkamery. Bluetooth pre diaľkové pripojenie mobilných zariadení je samozrejmosťou.\r\n\r\nNotebook je dodávaný s operačným systémom Windows 8, ktorý vďakanízkej náročnostinebude brzdiť čas zbytočným čakaním. Prelomová dlaždicová plocha spolu s novým prostredím prinášajednoduché a bezproblémové ovládanie. Súčasťou je Windows Store, otvárajúci bránu k množstvu užitočným aplikáciám. Pre prezeranie webového obsahu poslúži inovatívne Internet Explorer 10.', 'Notebook - AMD Dual Core E1-2500, 15.6 "LED 1366x768, RAM 2GB, AMD Radeon HD8240, HDD 500GB 5400 otáčok, DVD, WiFi, Webkamera, HDMI, čítačka pamäťových kariet, 4 čl batéria, Windows 8 64-bit (TE69KB- 12502G50Mnsk)', 3, 4, 12),
(439.55, 'Sony VAIO Fit 15E White', 'SONY', 'Pentium', 'Intel', 'HD4500', 'Intel', '4GB', '500GB', 15.5, 'Štýlový notebook, ktorý bude budiť pozornosť všade, kde ho vytiahnete. Minimalistický dizajn zaisťuje pohodlné používanie a vďaka rýchlemu procesor generácie Sandy Bridges vami bude notebook držať krok a umožní vám vychutnávať si naplno zábavu kdekoľvek na cestách. Multimediálne požitky umocňuje 15,5 "HD Ready displeja špičkovýzvuk s technológiou CLEARAUDIO +. Nadštandardné výbavu dopĺňa NFC čip pre rýchle bezdrôtové prenosy.', 'Notebook - Intel Pentium 2117 Ivy Bridge, 15.5 "LED 1366x768 lesklý, RAM 4GB DDR3L, Intel HD Graphics, HDD 500GB 5400 otáčok, DVD, WiFi, BlueTooth 4.0, NFC, webkamera, HDMI, USB 3.0, Windows 8 64-bit (SVF1521A6EW)', 4, 5, 10),
(734, 'Toshiba Satellite L50-A-19N', 'TOSHIBA', 'Corei7', 'Intel', 'GT740M', 'NVidia', '2GB', '750GB', 15.6, 'Notebook Tohsiba Satellite posúva hranice výkonu na úplne novú úroveň. Najnovšie 4jádrový procesor, podarená herné grafika a rozmerný disk sú tým najlepším, čo môže náruživý hráč dostať. Bezproblémovo strčí do vrecka aj väčšinu stolových počítačov so zameraním na hry. V jednom tele sú tiež zakomponované reproduktory Onkyo vo zvukovom systéme DTS Studio Sound, A tak si zábavu vychutnáte úplne novým, pohlcujúcim spôsobom.\r\n\r\nVďaka NVIDIA GeForce GT740 nebudete musieť robiť kompromisy ani u moderných počítačových hier. 384 CUDA jadier v architektúre Kepler sú nekompromisné silou zvládajúci vo vysokej kvalite aj také herné kúsky ako je Battlefield 4, Mass Effect 3, Max Payne 3, Far Cry 3 a mnohé ďalšie herné pecky.\r\n\r\nPod matnou klávesnicou sa skrýva 4jádrový procesor Intel Core i7 4700MQ. S technológiou Hyper-Threading sa chová ako 8jadrovú procesor a novo pridané inštrukcie prinášajú výkon pre všetky multimédiá i pre tie najnáročnejšie aplikácie typu úpravy fotografií i videa. Intel Turbo Boost 2 automaticky sleduje aktuálnu záťaž procesora, a v prípade potreby vyššieho výkonu ho přetaktuje, a poskytne tak potrebnú výpočtovú silu. Pre jeho podporu je vyčlenených slusnych 8 GB operačnej pamäte, Vďaka čomu si budete môcť dovoliť viac spustených aplikácií.', 'Notebook - Intel Core i7 4700QM Haswell, 15.6 "LED TruBrite 1366x768 lesklý, RAM 8GB, NVIDIA GeForce GT 740mm 2GB, HDD 750GB 5400 otáčok, DVD, Onkyo reproduktory, WiFi, Bluetooth, Webkamera, HDMI, USB 3.0, Windows 8 64-bit', 0, 6, 13),
(582.5, 'Acer Aspire V5-552G Touch červený', 'Acer', 'Aseries', 'AMD', 'HD8750', 'AMD', '6GB', '500GB', 15.6, 'Parádne tenký, osobito vyzerajúci notebook značky Acer vo vyrovnanej konfigurácii, ktoré dominuje vydarený 4jádrový procesor spoločnosti AMD. Na blízku sa ho ako kliešť drží pokročilá grafická karta AMD Radeon HD 8750. Je určený mobilným užívateľom, ktorí hľadajú prenosnú kanceláriu, ktorý by vydržala dlhú prácu, ale aj stroj ľahko zvládajúci bežná multimédiá vrátane slušné porcie hernej zábavy. Notebook je v štandardnom formáte 15,6 " a ponúkne aj pohodlné multidotykové ovládanie na displeji s označením CineCrystal.\r\n\r\nVýkon zabezpečí procesor AMD A8-5557 s automatickým taktovaním Turbo Core 3 až na 3,1 GHz. Veľkorysá pamäť v podobe 6 GB zvládne aj veľmi náročné úlohy, hry a aplikácie v mnohých oknách inovatívneho systému Microsoft Windows 8. Viac než dostatok priestoru zaistí pevný disk s kapacitou 500 GB. Vďaka Bluetooth pripojíte rôzne periférie as WiFi sa komfortne prihlásite na internet kdekoľvek v dosahu signálu.', 'Notebook - AMD Quad-Core A8-5557, kapacitný multidotykový 15.6 "LED CineCrystal 1366x768 lesklý, 6GB RAM, AMD Radeon HD8750M 2GB, HDD 500GB 5400 otáčok, WiFi, Bluetooth 4.0, Webkamera, HDMI, USB 3.0, 4 článková batéria, Windows 8 64 -bit', 1, 7, 14),
(406.17, 'Toshiba Satellite C55-A-1GK', 'TOSHIBA', 'Corei3', 'Intel', 'GT710M', 'NVidia', '4GB', '750GB', 15.6, 'Všestranne použiteľný notebook Toshiba Satellite C55 s veľmi výhodnou cenou a elegantným dizajnom. Je priamo stvorený pre domáce či kancelárske užívateľov, ktorým grafický čip v podobe NVIDIA GeForce 710M poskytne multimediálnu zábavu aj dostatok výkonu v nenáročných počítačových hrách. Ďalej vám ponúkne plnohodnotnú klávesnicu is numerickou časti, nadštandardný displej a čas na batériu až 3,5 hodiny. Kdekoľvek môžete počúvať kvalitný zvuk vylepšený technológiou DTS Sound.\r\n\r\nPre prehrávanie filmov alebo tvorenie záloh je multiformátová DVD napaľovacia mechanika. Pre svoje dáta a aplikácie využijete disk s veľkou kapacitou 750 GB. Nezabudlo sa na pripojenie do siete káblom alebo bezdrôtovou WiFi a videohovory uskutočníte cez webkameru. Digitálne fotografi určite ocenia čítačku kariet pre najčastejšie používané formáty kariet SD a MMC. Mobilné nadšenci naopak uvítajú bezdrôtový Bluetooth pre jednoduchú synchronizáciu. Procesor Intel Core i3 3110 z vydarenej rodiny Ivy Bridgepodáva spolu so 4 GB operačnej pamäte svedomitý výkon. Súčasťou notebooku je vyspelý operačný systémMicrosoft Windows 8.1, Ktorý rozširuje úspešné "osmičky" o ďalšie užitočné funkcie.', 'Notebook - Intel Core i3 3110 Ivy Bridge, 15.6 "LED 1366x768 lesklý TruBrite, RAM 4GB, NVIDIA GeForce 710M 1GB, HDD 750GB 5400 otáčok, DVD, WiFi, Bluetooth 4.0, webkamera, HDMI, USB 3.0, Windows 8.1 64-bit', 2, 8, 12),
(590.83, 'Acer Aspire TimeLineU M5-581TG', 'ACER', 'Corei7', 'Intel', 'GT730M', 'NVidia', '6GB', '500GB', 15.6, 'Inovatívne ultrabook značky Acer s porciou výkonu is úctyhodnouvýdržou až 8 hodín. Na prvý pohľad zaujme tenkosťoušasi do 21 mm! Je presne prispôsobený pre mobilné použitie. Tým je určený veľmi náročným užívateľom, ktorí hľadajú mobilnú kanceláriu, ktorý by s nimi udržala celý deň krok. Zároveň však stroj zvládne aj hranie hier, náročné programy pre prácu s grafikou a videami alebo multimédiá. Pri prenášaní okrem výdrže poteší ajhmotnosť 2,15 kg!\r\n\r\nDostatok priestoru pre dáta zaistí kapacitou500 GB na očkovacom disku s podporou zrýchľujúceho SSD disku. Vďaka tomu bude prechod zo spánku otázkou okamihov. Rýchly prenos súborov zaisťujú rozhranie USB 3.0 a Bluetooth 4.0. Aj napriek veľmi tenké prevedenie sa našlo miesto preDVD napaľovacia mechaniku. So zvukovým systémomDolby Home Theater v4si užijete plný zvuk kamkoľvek vyrazíte.\r\n\r\nPre použitie je predinštalovaný moderný operačný systémMicrosoft Windows 8. Rýchly chod je na technologicky vyspelom procesora z rodinyIvy Bridge,Intel Core i7 3517. Jeho technológiaIntel Turbo Boost 2sa vyrovná aj s veľmi vysokým zaťažením, kedy automaticky zdvihne frekvenciu. Dokáže tak plne uspokojiť všetky aplikácie.', 'Ultrabook - Intel Core i7 3537 Sandy Bridge, 15.6 "LED CrystalBrite 1366x768 lesklý, 6GB RAM, NVIDIA GeForce GT 730mm 1GB DDR5, HDD 500GB 5400 otáčok + 20GB Cache pre zrýchlenie behu OS, DVD, WiFi, Bluetooth 4.0, Webkamera, HDMI, Windows 8 64-bit', 0, 9, 5),
(809.98, 'ASUS N750JV-T4148H', 'ASUS', 'Corei7', 'Intel', 'GT750M', 'NVidia', '8GB', '750GB', 17.3, '17palcový notebook zvádzajúce najmä pokročilou grafickou kartou NVIDIA GeForce GT750 a najnovším 4jádrovým procesorom s oporou 8 GB operačnej pamäte v krásnom tele s metalickým povrchom. Architektúra procesora Haswell s automatickým taktovaním Intel Turbo Boost 2 sa nedostane nikdy do úzkych, kým grafika s jadrom Kepler prinesie pôsobivý výkon na poli multimédií. Novo riešené chladenie s 2 veľkými ventilátormi zaručuje rezervu pre už spomínané automatické taktovania. Vďaka tomu svižne zvláda aj herné zábavu, ak nevyžadujete detaily do poslednej bodky. Je voľbou pre všetkých, ktorí vymenia riadnu porciu výkonu a veľký LCD za cestovné veľkosť, pretože notebook používajú výlučne doma medzi miestnosťami a počítač len príležitostne prenáša alebo preváži.\r\n\r\nMatný Full HD displej má nezvyčajne široké pozorovacie uhly, A tak vám pôžitky nenaruší pohľad mierne z boku ani odlesky svetla. Pre kompletný audiovizuálny zážitok má doprovod 4 reproduktorov s technológiou SonicMaster Premium. Vývoj v spolupráci so spoločnosťou Bang & Olufsen ICEpower sa odrazil na tých najlepších vlastnostiach. Spolu s profesionálnymi nástrojmi MaxxAudio pre spracovanie zvuku podajú vysokú vierohodnosť zvuku a pôsobivé basy aj pri vyššej hlasitosti.\r\n\r\nVymoženosťou je aj ASUS Super Hybrid Engine II s funkciou Instant On. Tá zariadi prechod z režimu spánku do 2 sekúnd! Ak si teda potrebujete odskočiť a potom vás nebaví netrpezlivo čakať ako bude systém funkčný, táto funkcia vás tohto zbaví. Dostanete tiež prístup ku cloudovému úložisku, kde môžete mať synchronizované údaje s notebookom, tabletom aj smartphonom.', 'Notebook - Intel Core i7 4700HQ Haswell, 17.3 "LED 1920x1080 matný, RAM 8GB, NVIDIA GeForce GT 750M 2GB, HDD 750GB 7200 otáčok, DVD, WiFi, Bluetooth 4.0, Webkamera, HDMI 1.4, USB 3.0,čítačka kariet, Windows 8 64-bit', 3, 10, 14),
(966.67, 'MSI GT60 2OC-205X', 'MSI', 'Corei5', 'Intel', 'GT770M', 'NVidia', '8GB', '750GB', 15.6, 'Špičkový notebook značky MSI s výkonnou herné grafikou v exkluzívne spracovanom šasi štandardného formátu je postastaven na 2jádrovém procesora Haswell, nechýba mu optická DVD SuperMulti mechanika, Špeciálna sieťová karta Bigfoot Killer, Rýchle eSATA rozhrania a samozrejme ani extrémne výkonná grafická karta nVidia. Je jasným kandidátom pre grafické pôžitky herných príbehov, ale zvládne uspokojiť všetky požiadavky aj tých najnáročnejších užívateľov. Notebook je dodávaný bez operačného systému.<br>\r\nVšetko dianie sa odohráva na kvalitnom displeji s Full HD rozlíšením. Ocenia ho všetci skalní priaznivci hier, ktorí chcú mať pre prenášanie kompletné herné stanicu prevyšujúcu väčšinu stolových počítačov. Odmenou za to budiž luxusná výbava zahŕňajúca aj zvukový systém Dynaudio pre hlasitý a vo všetkých úrovniach plnohodnotný zvuk. Samozrejmosťou je certifikácia THX.<br>\r\nV útrobách je uložený rýchly pevný disk, Ktorý zaistí vysokú kapacitu 750 GB. Rotuje rýchlosťou 7200 RPM. Obraz následne môžete preniesť na moderné televízie cez HDMI. Pre pripojenie externého disku je pripravená trojica najnovších rozhrania USB 3.0.\r\n<br>\r\nTento stroj bol designovaný presne pre potreby hráčov, najmä tých, ktorí sú najaktívnejší vo chvíľach voľna - v noci. MSI v spolupráci s profesionálom v oblasti herných periférií výrobcom Steelseries vyvinuli revolučný systém viacfarebného podsvietenia klávesnica pre rýchlu a prehľadnú orientáciu. Pre maximálne pohodlie sú klávesy zväčšené az ľavej strany bolo úplne odstránené tlačidlo Windows.\r\n<br>\r\nNotebook je založený na výpočtovej sile procesora z novinkové rodiny Haswell - Intel Core i5 4200. Pri využití technológie Intel Turbo Boost 2 je schopný automaticky taktovať, Čím sa stabilne vyrovná is vysokým zaťažením aplikáciami. Zakončením celej hardvérové skladby je pre hry stvorená grafická karta NVIDIA GeForce GTX770M sa 3 GB a obsahujúce dokonca 960 jadier CUDA, Takže si určite užijete veľa hernej zábavy s krásne uhladenou grafikou v prostredie DirectX 11.', 'Notebook - Intel Core i5 4200 Haswell, 15.6 "LED 1920x1080 antireflexnou, RAM 8GB DDR3, NVIDIA GeForce GTX 770mm 3GB, HDD 750GB 7200 otáčok, DVD, WiFi, Bigfoot Killer LAN, Bluetooth 4.0, HDMI, USB 3.0, HD webkamera, čítačka kariet, 9-článková batéria.', 1, 11, 15),
(2824.33, 'MSI GT70 2OD Dragon Edition 2 Extreme', 'MSI', 'Corei7', 'Intel', 'GT780M', 'NVidia', '32GB', '750GB', 17.3, 'Luxusné herný notebook značky MSI v edícii Dragon má ešte výkonnejšie grafiku a najnovší procesor Haswell zo série Intel Extreme. Notebook má to najlepšie z hardvéru, sieťovú konektivitu karty Bigfoot Killer s minimálnou odozvou a antireflexný Full HD displej pre mimoriadne kvalitný obraz bez narušenia odlesky svetla. Dokonca sa pýši Blu-ray napaľovačkou a má hneď 3 SSD disky v exkluzívnom prekladanom režime RAID 2, Vďaka čomu dosahujú až 15x vyššiu rýchlosť zápisu ako klasický disk s platňami. Teoretická rýchlosť dosahuje až 1500 MB/s! Je jasným kandidátom pre grafické pôžitky moderných počítačových hier, ale zvládne uspokojiť všetky požiadavky aj tých najnáročnejších užívateľov. Multimediálne dravosť dokonale vystihuje exkluzívny dizajn. <br><br>\r\nTento výkonný stroj je obdarený grafikou NVIDIA GeForce GTX780M využívajúci revolučnú architektúru dodávajúca oproti predchádzajúcej generácii extrémny výkon. Je nástupcom najvyššieho mobilného modelu GTX680. V porovnaní s GeForce GTX770M v "obyčajnej" edíciu môžu používatelia získať až ďalších viac než 35% výkonu. Bleskovo rýchly antialiasing sa automaticky zapne v obrovskej škále hier, a vy tak získate maximálne prepracovaný herný obraz a najlepšiu kompatibilitu s NVIDIA grafikou. Spolu s technológiou NVIDIA PhysX prinesie do vášho hrania dynamiku a interaktivitu prostredia ako v realite.<br><br>\r\nZákladom je však 4jádrový procesor rodiny Intel Haswell s novou inštrukčnú sadu zvanú Haswell New Instruction pre ešte vyššiu rýchlosť spracovania za všetkých situáciách. Nechýba obľúbená rezerva výkonu v podobe automatického taktovania Intel Turbo Boost 2. To všetko pod exkluzívnym chladiacim systémom Cooler Boost 2. Ten je oproti predchodcovi z roku 2012 až o 15% výkonnejšie a zároveň až o 25% menej hlučný! Vďaka tomu udržuje stabilnú teplotu a výkon aj pri najnáročnejších situáciách.<br><br>\r\nJedinečná funkcie NOS používa batériu aj napájací adaptér v rovnakom čase! Kombináciou chladiaceho systému Cooler Boost 2 a NVIDIA GPU Boost 2.0 môže pomôcť používateľom, aby dosiahli vyššie frekvencie grafiky, a teda aj výkonu až o 10%. Akonáhle je celkové využitie energie cez maximum adaptéra, systém automaticky zapne "NOS" na podporu udržania GPU Boost.', 'Notebook - Intel Core i7 4930MX Haswell, 17.3 "LED 1920x1080 antireflexnou, RAM 32GB DDR3L, NVIDIA GeForce GTX 780mm 4GB, 3x SSD 128GB + HDD 750GB 7200 otáčok, BluRay, WiFi, Killer Doubleshot LAN, Bluetooth 4.0, HDMI, USB 3.0, eSATA, HD webkamera, čítačka kariet, 9-článková batéria, klávesnica podsvietená Steelseries, Windows 8 64-bit', 2, 12, 9);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
